### PR TITLE
Add HttpResponderBundle

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by ro0NL** [comment]
cc @kunicmarko20

**Comment by Nyholm** [comment]
Thank you. 
It seams like you have submitted a recipe without any config. Flex is smart enough to install this bundle without a recipe. I suggest closing this PR.

**Comment by ro0NL** [comment]
AFAIK it doesnt work out-of-the-box due the namespace (bundle in a lib basically). Just tested it and can confirm bundles.php is not updated.

**Comment by Nyholm** [comment]
You are correct. I missed that fact. 

Then Im all happy with this PR. 
Thank you

**Pull request merged**
