### PR TITLE
add recipe for BeelabTestBundle

### PR DESCRIPTION
**Pull request by garak**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. 

We do only accept apache and MIT licences at this point. Do you want to consider changing to a more generous license?

**Comment by garak** [comment]
Instead, what about being less strict about accepted licenses? I also opened an [issue on Flex](https://github.com/symfony/flex/issues/221)

**Comment by alcaeus** [comment]
@Nyholm while I agree that you want to whitelist acceptable licenses, there shouldn't be a problem adding the LGPL to the list. I get why there may be issues with GPL, but the LGPL should be fine.

**Comment by Nyholm** [comment]
Im happy with this recipe. Lets see how the discussion in https://github.com/symfony/flex/issues/221 goes.

**Comment by fabpot** [comment]
@symfony-flex-server review

**Pull request merged**
