### PR TITLE
WIP: OverblogGraphQLBundle recipe

### PR DESCRIPTION
**Pull request by renatomefi**
| Q             | A
| ------------- | ---
| License       | MIT

Follow up from: https://github.com/symfony/recipes/pull/183

How to test:
- `composer create-project "symfony/skeleton" sf-flex-graphql-recipe && cd sf-flex-graphql-recipe`
- `SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes-contrib/85 composer req cli:^3.3 webserver:^3.3 twig:^3.3 overblog/graphql-bundle:dev-master`
- `bin/console server:run`
- http://127.0.0.1:8000/graphiql

### CODE REVIEW

**Comment by stof** [comment]
use `composer req overblog/graphql-bundle:dev-master`, not `master` to get a valid version.

@fabpot could you ensure that the https://symfony.sh server always responds in JSON format when being asked for recipes ?

**Comment by stof** [comment]
@renatomefi the endpoint you added in the env variable is not the one given in the github deployment of this PR: https://symfony.sh/r/github.com/symfony/recipes-contrib/85

**Comment by renatomefi** [comment]
@stof indeed, I was following the blog post tutorial: http://fabien.potencier.org/symfony4-contributing-recipes.html
Maybe it could also be updated

And indeed the problem before was caused due to the endpoint not returning JSON, thus after the deployment it worked fine and I'm being able to test it

**Comment by stof** [comment]
Well, the URL scheme was changed after that.

@fabpot you may want to add a warning in this blog post to have people getting this URL from the deployment reported on github (which will always be uptodate, unless the server is buggy when reporting the URL) instead of having them follow an old convention found in the blog post.

**Comment by renatomefi** [comment]
0.9.0-BETA3 is tagged for the bundle, you can test via:
`SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes-contrib/85 composer req cli:^3.3 webserver:^3.3 twig:^3.3 overblog/graphql-bundle:dev-master#0.9.0-BETA3`

**Comment by stof** [comment]
@renatomefi don't use a `dev-master` version with a commit-override set to the tag. Require the beta tag instead (so that composer actually gets the metadata corresponding to the tag rather than the latest master):

```bash
SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes-contrib/85 composer req cli:^3.3 webserver:^3.3 twig:^3.3 overblog/graphql-bundle:0.9.0-BETA3
```

**Comment by renatomefi** [comment]
@stof great tip, thanks!
So I think we are ready to merge when 0.9 is out of beta then.
@mcg-web what do you think?

**Comment by mcg-web** [comment]
Yes need some more long run again and 0.9 will be ready to be release... This can wait until to be merge I think.

**Comment by renatomefi** [comment]
@stof @fabpot Is there something wrong with the recipes PR deployment?
https://symfony.sh/r/github.com/symfony/recipes-contrib/85

The link isn't working anymore

**Comment by renatomefi** [comment]
@stof @fabpot could you please look at it? Thanks :)

**Comment by renatomefi** [comment]
I'll start a new PR, for some reason there is a crazy cache going on here and failing builds as you can see in the history.

**Pull request closed without merging**
