### PR TITLE
* Add a recipe for coka/pagination-bundle

### PR DESCRIPTION
**Pull request by CedrickOka**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
Im happy to merge if you remove the default parameters or the parameters that do not serve as an example (the ones likely to be changed).

**Comment by CedrickOka** [comment]
Hi @Nyholm,
all default parameters have been removed.

**Comment by Nyholm** [comment]
Awesome. Im just waiting for the CI to be green

**Comment by CedrickOka** [comment]
Great, all CIs are green, thank you in advance.

**Pull request merged**
