### PR TITLE
Add GazeSymfonyBundle recipe

### PR DESCRIPTION
**Pull request by daanvanberkel**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by daanvanberkel** [comment]
Hello @Nyholm can you take a look at this pull request, please?

**Comment by Nyholm** [comment]
Could you retrigger Travis please?

**Comment by daanvanberkel** [comment]
> Could you retrigger Travis please?

Done

**Review by Nyholm — APPROVED** [review]
Thank you

**Pull request merged**
