### PR TITLE
add recipe for pentatrion/vite-bundle

### PR DESCRIPTION
**Pull request by lhapaipai**
| Q             | A
| ------------- | ---
| License       | MIT

Hi,
This Pull Request adds the recipe for the [pentatrion/vite-bundle](https://github.com/lhapaipai/vite-bundle).

### CODE REVIEW

**Review by Nyholm — COMMENTED** [review]
Hey. 

I suggest to put the css/js/ts in your package and use `copy-from-package`. I also think we should remove the `yaml` file because it does not provide any config, it is just comments.

**Comment by lhapaipai** [comment]
Hi @Nyholm, thanks for your review,
do you think i should move too the `vite.config.js` and `package.json` files into my package ?

**Comment by Nyholm** [comment]
Yes. That sounds like a good idea. Also app.js and app.css

**Review by Nyholm — APPROVED** [review]
Thank you

**Pull request merged**
