### PR TITLE
Added hostnet/form-handler-bundle/1.2

### PR DESCRIPTION
**Pull request by iltar**
Added the hostnet/form-handler-bundle: https://github.com/hostnet/form-handler-bundle/wiki

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @iltar.

**Comment by stof** [comment]
@fabpot this recipe is now useless

**Comment by fabpot** [comment]
deleted in 3dba6fb

**Comment by iltar** [comment]
Something as simple like this will now be auto-configured?

**Comment by stof** [comment]
@iltar if you have `type=symfony-bundle` in your composer.json, flex will now try to generate a default recipe when there is none in the repository. This recipe is only registering the bundle for all environments.
This works if flex manages to guess the bundle class name (which I think is the case for this bundle)

**Comment by stof** [comment]
Well, actually, the bundle does not define this type, so it would still need a change. But I think this can be done easily in the bundle

**Comment by iltar** [comment]
@stof indeed it's missing, I'll add it.

**Pull request merged**
