### PR TITLE
support enqueue 0.9

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
Isn’t this a duplicate of #565?

**Comment by OskarStark** [comment]
> Isn’t this a duplicate of #565?

You are absolutely right, thank you!
We can close it here, but on question, how is the best practice:

We have enqueue-bundle which installs added this env: `ENQUEUE_DSN` and now, for every transport I install, I get a new part in .env.dist file and a new defined `ENQUEUE_DSN`. This can result in weird results, because the last registered ENV "wins":

```
###> enqueue/enqueue-bundle ###
ENQUEUE_DSN=amqp+ext://guest:guest@rabbitmq:5672
###< enqueue/enqueue-bundle ###

###> enqueue/null ###
ENQUEUE_DSN=null://
###< enqueue/null ###

###> enqueue/sqs ###
ENQUEUE_DSN=sqs://
###< enqueue/sqs ###
```

In this case it uses the sqs one.... which is not properly configured and results in an exception.

Imo we should only expose/create/add this specific ENV only for the bundle itself.
For the transports it looks more like a documentation on how this DSN should start to get it to work, but a text-output after adding a transport looks more appropriate to me.

//cc @makasim

**Comment by makasim** [comment]
The alternative would be to use separate DSN names and the bundle config, for example, AMQP_DSN, REDIS_DSN, SQS_DSN and so no and config:

```
enqueue:
    amqp:
        transport: '%env(AMQP_DSN)%'
```

There some disadvantages too:

* It's not that clear which one is a default
* Many config files 
* DSN names could collide with other recipes.

**Comment by OskarStark** [comment]
My proposal would be to only use `ENQUEUE_DSN` which avoids collisions with other envs/bundles and after installing a transport show a message like:

```
To use SQS transport, update ENQUEUE_DSN like this:

    ENQUEUE_DSN=sqs://.....

```

**Comment by makasim** [comment]
I like it.

**Comment by OskarStark** [comment]
> I like it.
😄 

I would provide a PR after #565 was merged and will do this for 0.8 version, too

**Comment by makasim** [comment]
@Nyholm it's ready to go.

**Comment by makasim** [comment]
@Nyholm what can I do to get this merged?

**Comment by Nyholm** [comment]
Great. Thank you

**Comment by OskarStark** [comment]
Please merge this instead: https://github.com/symfony/recipes-contrib/pull/565

**Comment by Nyholm** [comment]
> Please merge this instead: #565

Thank you. I just read them both and was just about to ask.

**Pull request closed without merging**
