### PR TITLE
Recipe for wedrix/watchtower

### PR DESCRIPTION
**Pull request by Wedrix**
| Q             | A
| ------------- | ---
| License       | MIT
| Packagist     | https://packagist.org/packages/wedrix/watchtower

### CODE REVIEW

**Comment by Wedrix** [comment]
Intended for Symfony 6.1

**Comment by OskarStark** [comment]
The PHP code should be part of the package, not the recipe IMHO.
A recipe is only meant for configuration of the package

**Comment by Wedrix** [comment]
> The PHP code should be part of the package, not the recipe IMHO. A recipe is only meant for configuration of the package

Absolutely. I'll work on a proper bundle soon.

**Comment by fabpot** [comment]
What about closing it for now as we won't merge this PR which contains mostly PHP code that should be part of a bundle instead?

**Review by fabpot — CHANGES_REQUESTED** [review]
Recipes should not contain so many PHP classes. These should probably be moved to the bundle itself or generated by a command from the bundle.

**Comment by Wedrix** [comment]
Closing for now.

**Pull request closed without merging**
