### PR TITLE
Add recipe for elephantly/kahlan-bundle

### PR DESCRIPTION
**Pull request by Brunty**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
@symfony-bot review please

**Comment by Nyholm** [comment]
@symfony-flex-server review please.. pretty please?

**Comment by Nyholm** [comment]
Great! @Brunty could you make some updates to your bundle so it passes the validation?

https://symfony.sh/r/github.com/symfony/recipes-contrib/100

**Comment by Brunty** [comment]
@Nyholm will do! Need to do some work on it anyway :) (not my bundle)

**Comment by Nyholm** [comment]
I see that this PR did not get merged in February. It is because you have "WIP" in the title. Please update the title in order to get this merged.

**Pull request merged**
