### PR TITLE
add recipe for whiteoctober/WhiteOctoberPagerfantaBundle

### PR DESCRIPTION
**Pull request by gabiudrescu**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by gabiudrescu** [comment]
@Nyholm 

I have opened a PR to fix the problem with the missing dependency, waiting for it to be accepted and merged.

Regarding the configuration, the repo readme says, I quote:

```
This project is not yet configured with Symfony Flex, so this change to config/bundles.php won't be done automatically.
```

And I don't remember to have got this bundle automatically added to my bundle list when I installed it without my PR to flex. But I will try again.

My main desire was to get flex to create the pagerfanta.yaml on my behalf so I can customize at a later point.

Is there any chance to get this PR merged as it is?

**Comment by Nyholm** [comment]
There is no difference for the user if we merge this PR or not. The bundle will still be installed and work exactly the same way, right?

**Comment by emodric** [comment]
@Nyholm Currently, for some reason, the bundle is not autoactivated if installed with flex, no auto generated recipe is executed.

I haven't been able to deduce why.

**Comment by emodric** [comment]
The reason was non standard PSR-4 config: https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/pull/205

**Comment by Nyholm** [comment]
Great. I seen you use PSR-4 now. The bundle will be installed with Flex. We dont need a recipe with the default config. 

#eu-fossa

**Pull request closed without merging**
