### PR TITLE
Added Pronto-AM MobileBundle

### PR DESCRIPTION
**Pull request by troovers**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
Any updates here?

**Comment by troovers** [comment]
Hi, I haven't had the chance to improve it sorry. What do you mean by isolating the recipes?

**Comment by Nyholm** [comment]
I mean: one package - one recipe. 

Right now, this recipe modifies multiple packages.

**Comment by Nyholm** [comment]
Closing due inactivity. 

#eu-fossa

**Pull request closed without merging**
