### PR TITLE
Add CosmonovaRnD recipes

### PR DESCRIPTION
**Pull request by Besedin86**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
Could you make sure Travis is happy?

**Comment by Nyholm** [comment]
Any updates here?

**Comment by Besedin86** [comment]
@Nyholm Sorry for late answer. Currently my packages depends on developer version of third party package. So that I can't fix it now till it will be in dev.

**Comment by Nyholm** [comment]
Okey. Please get back to me when your dependencies are stable.

**Comment by Nyholm** [comment]
Any updates on this PR?

**Comment by Nyholm** [comment]
Closing due inactivity. 

#eu-fossa

**Pull request closed without merging**
