### PR TITLE
Add recipe for php-bug-catcher/bug-catcher

### PR DESCRIPTION
**Pull request by tito10047**
| Q             | A
| ------------- | ---
| License       | MIT
| Packagist     | https://packagist.org/packages/php-bug-catcher/bug-catcher

### CODE REVIEW

**Comment by tito10047** [comment]
I cant get working this recipe. all the time I get message "Configuring php-bug-catcher/bug-catcher (>=1.0.4): From auto-generated recipe"
Can somebody help me get it work?

I do whot is in this pr and install package with command ```composer require 'php-bug-catcher/bug-catcher:^1.0.4'```

**Comment by tito10047** [comment]
I can't get work this recipie.
this is in console ``` Configuring php-bug-catcher/bug-catcher (>=1.0): From github.com/symfony/recipes-contrib:main``` so is good, but recipie is nt executed.

when ai run command ```composer recipes:update php-bug-catcher/bug-catcher```
this error is writed:
```Failed to download recipe: The "https://raw.githubusercontent.com/symfony/recipes-contrib/flex/pull-1659/archived/php-bug-catcher.bug-catcher/d3f48ef31320f551bbb8ebc3937d7615f01405dd.json" file could not be downloaded (HTTP/2 404 )```

**Comment by fabpot** [comment]
A recipe should only be about the package you configure. Here, you have too many other configs. That cannot be merged as is.

**Comment by tito10047** [comment]
Yes, but this is not a package, this is the entire application. An application that you can easily expand with your own code.

If you can't merge it, close this PR. 

But it's annoying to force people to set all this settings manually when they want to run my application. just see how huge is docs for this first run [docs](https://github.com/php-bug-catcher/bug-catcher#installation)

Do you have any recommendations on how to do it better?

**Comment by OskarStark** [comment]
You can create and provide a setup command, creating such config?

**Comment by tito10047** [comment]
Ok, I will try, thanks :)

**Comment by tito10047** [comment]
> You can create and provide a setup command, creating such config?

This is good idea, but can't be work. 

When I install my budnle, then project is broken because missing configuration required for this bundle. So I can't run command which need to generate this config.

Any other idea?

**Pull request closed without merging**
