### PR TITLE
Add recipe for the facile-it/MongoDB-Bundle

### PR DESCRIPTION
**Pull request by Jean85**
| Q             | A
| ------------- | ---
| License       | MIT

This adds the recipe for https://github.com/facile-it/mongodb-bundle/

### CODE REVIEW

**Comment by Jean85** [comment]
The CI build will not pass without the `ext-mongodb` extension. How can I fix it?

**Comment by Nyholm** [comment]
Thank you for this PR. 

Do not worry too much about travis. It is just a check that things does not blow up... (Maybe we should tell composer to ignore system requirements??)

I ran this recipe manually and I found a small issue. 

screen shot 2018-01-21 at 10 37 06

**Comment by Jean85** [comment]
Thanks @Nyholm, but ignoring requirements could lead to issues anyway.

Thanks for spotting that; it's the kind of stuff that the Travis build should detect..

**Comment by Nyholm** [comment]
I still get the same error. Does it work when you try it on a new project?

**Comment by Jean85** [comment]
I just installed a fresh Symfony 4 skeleton to try this out and I didn't get the same error:
```
$ composer require symfony/flex
    1/1:        http://packagist.org/p/provider-latest$c1bb23f08d2df9dfdd10dab462d0a554a8d113a94482cd4fdfdd2d7d5dadd311.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Using version ^1.0 for symfony/flex
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/flex (v1.0.67): Loading from cache
Writing lock file
Generating autoload files
Symfony operations: 1 recipe (e4c7f0e31342ddbaf13589e57b3b0446)
  - Configuring symfony/flex (>=1.0): From github.com/symfony/recipes:master

$ composer require facile-it/mongodb-bundle --ignore-platform-reqs
Using version ^0.6.5 for facile-it/mongodb-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 18 installs, 0 updates, 0 removals
  - Installing symfony/routing (v4.0.3): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.6.0): Loading from cache
  - Installing symfony/http-foundation (v4.0.3): Loading from cache
  - Installing symfony/event-dispatcher (v4.0.3): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v4.0.3): Loading from cache
  - Installing symfony/http-kernel (v4.0.3): Loading from cache
  - Installing symfony/finder (v4.0.3): Loading from cache
  - Installing symfony/filesystem (v4.0.3): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/dependency-injection (v4.0.3): Loading from cache
  - Installing symfony/config (v4.0.3): Loading from cache
  - Installing psr/simple-cache (1.0.0): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/cache (v4.0.3): Loading from cache
  - Installing symfony/framework-bundle (v4.0.3): Loading from cache
  - Installing mongodb/mongodb (1.2.0): Loading from cache
  - Installing facile-it/mongodb-bundle (0.6.5): Loading from cache
Writing lock file
Generating autoload files
Symfony operations: 3 recipes (00428cba52a285ddd2d4c324300ca0c3)
  - Configuring symfony/framework-bundle (>=3.3): From github.com/symfony/recipes:master
  - Configuring symfony/routing (>=4.0): From github.com/symfony/recipes:master
  - Configuring facile-it/mongodb-bundle (>=0.6.5): From auto-generated recipe
```
The `--ignore-platform-reqs` was due to the fact that I'm missing the MongoDB extension.
I would like to fix the CI and install that extension... Is there any way to do it?

**Comment by Nyholm** [comment]
See the steps here to tell flex to use your fork: 
https://symfony.sh/r/github.com/symfony/recipes-contrib/259

**Comment by Jean85** [comment]
I created an empty Flex project and followed your instructions, and it worked at the first try:

```
$ composer req "facile-it/mongodb-bundle:^0.6"
Warning: Using https://symfony.sh/r/github.com/symfony/recipes-contrib/259 as the Symfony endpoint
./composer.json has been updated
Warning: Using https://symfony.sh/r/github.com/symfony/recipes-contrib/259 as the Symfony endpoint
Loading composer repositories with package information
Updating dependencies (including require-dev)

Prefetching 2 packages 🎶
  - Downloading (100%)

Package operations: 18 installs, 0 updates, 0 removals
  - Installing symfony/routing (v4.0.4): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.7.0): Loading from cache
  - Installing symfony/http-foundation (v4.0.4): Loading from cache
  - Installing symfony/event-dispatcher (v4.0.4): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v4.0.4): Loading from cache
  - Installing symfony/http-kernel (v4.0.4): Loading from cache
  - Installing symfony/finder (v4.0.4): Loading from cache
  - Installing symfony/filesystem (v4.0.4): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/dependency-injection (v4.0.4): Loading from cache
  - Installing symfony/config (v4.0.4): Loading from cache
  - Installing psr/simple-cache (1.0.0): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/cache (v4.0.4): Loading from cache
  - Installing symfony/framework-bundle (v4.0.4): Loading from cache
  - Installing mongodb/mongodb (1.2.0): Loading from cache
  - Installing facile-it/mongodb-bundle (0.6.5): Loading from cache
Writing lock file
Generating autoload files
Symfony operations: 3 recipes (262f8a773dad76ae54828602c6cd0176)
  - Configuring symfony/framework-bundle (>=3.3): From github.com/symfony/recipes:master
  - Configuring symfony/routing (>=4.0): From github.com/symfony/recipes:master
  - Configuring facile-it/mongodb-bundle (>=0.6): From github.com/symfony/recipes-contrib:259
```
I obviously installed the `ext-mongodb` first, but still, no issues.

**Pull request merged**
