### PR TITLE
Add ApiPlatformMsBundle recipe

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
Travis is not happy with this. Do your bundle has a dependency on twig?

**Comment by mtarld** [comment]
> Travis is not happy with this. Do your bundle has a dependency on twig?

Yes, I've seen it. It's kind of strange because twig is only in `require-dev`.
I'll investigate it

**Comment by mtarld** [comment]
It seems like version `2.6` of `api-plaform/core` introduced a regression:

```bash
$ composer create-project symfony/skeleton:^4.4 # Same goes for 5.x versions
$ cd skeleton
$ composer req api-platform/core:2.6
[...]
Script cache:clear returned with error code 1
!!  
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
!!                                                                                 
!!    The service "api_platform.swagger.action.ui" has a dependency on a non-exis  
!!    tent service "twig". 
```
Whereas 
```bash
$ composer create-project symfony/skeleton:^4.4
$ cd skeleton
$ composer req api-platform/core:2.5
[...]
Executing script cache:clear [OK]
```

Nothing directly related to the bundle I guess.

An issue is talking about it: https://github.com/api-platform/core/issues/1149

**Comment by mtarld** [comment]
I created a PR aiming to fix it: https://github.com/api-platform/core/pull/4187

**Review by Nyholm — APPROVED** [review]
Awesome. Thank you

**Pull request merged**
