### PR TITLE
Add recipe for netgen/layouts-core

### PR DESCRIPTION
**Pull request by emodric**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by emodric** [comment]
Hi! As with #694, the CI failure is caused by latest version of `ocramius/proxy-manager` in combination with `ignore-platform-reqs` option used by Travis.

**Comment by emodric** [comment]
Hi, can anyone help get this merged? @nicolas-grekas for example :)

Thanks!

**Comment by nicolas-grekas** [comment]
@emodric can you please embed the patch in #727 to see how it goes on Travis?

**Comment by emodric** [comment]
@nicolas-grekas Done. Travis build now passes (yay!), but PR does not validate any more :/

**Comment by nicolas-grekas** [comment]
Thanks for the confirmation, can you please rebase now? We merged the other PR.

**Comment by emodric** [comment]
@nicolas-grekas Done!

**Comment by fabpot** [comment]
@symfony-flex-server review please

**Comment by emodric** [comment]
Thank you @fabpot @nicolas-grekas!

**Pull request merged**
