### PR TITLE
Add PHP-CS-Fixer recipe

### PR DESCRIPTION
**Pull request by jdecool**
| Q             | A
| ------------- | ---
| License       | MIT

Add recipe for the [PHP-CS-Fixer](http://github.com/friendsofphp/php-cs-fixer) lib.

### CODE REVIEW

**Comment by fabpot** [comment]
Do we really need to have such a long config? /cc @keradus

**Comment by jdecool** [comment]
It's the default file that use in the project.

But maybe, we can reduce it to a minimal version that check PSR-2 convention and allow user to add more configuration.

**Comment by keradus** [comment]
@fabpot not, for sure not!

> It's the default file that use in the project.

@jdecool this is not good approach to follow ;)
- we have very tweaked ruleset, yet we shall ask ppl to follow well-established one instead
- risky by default is not good idea
- workaround for fabbot.io is not needed at all for all projects except dev line of PHP CS Fixer itself

IMO, how it shall look like: https://github.com/symfony/recipes/pull/220

**Comment by fabpot** [comment]
closing in favor of symfony/recipes#220

**Pull request closed without merging**
