### PR TITLE
Added KMSFroalaEditorBundle recipe

### PR DESCRIPTION
**Pull request by jmsche**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by jmsche** [comment]
I think it's going to need the following PR in the other repo to be merged: https://github.com/froala/KMSFroalaEditorBundle/pull/89

**Comment by Nyholm** [comment]
Thank you for this PR. Can you see why travis is failing? Maybe you need to require twig?

**Comment by jmsche** [comment]
I'll have to wait for a tag/release on their side to fix the PR :)

**Comment by jmsche** [comment]
Hello Tobias @Nyholm,

The PR is now ok as a new release has been pushed in KMS's repository.

However Travis CI seems to be failing as the bundle requires symfony/console:^4.3, but I think this can't work as it is tested against Symfony ^3.4 as well.

The PR passes for Symfony ^4.0.

**Pull request merged**
