### PR TITLE
added svc-bundles to recipes-contrib

### PR DESCRIPTION
**Pull request by Sven-Ve**
| Q             | A
| ------------- | ---
| License       | MIT

**To symfony core mergers**
Please approve my PR :-)

**Important:**
> Cannot autowire service "svc_profile.service.change-mail-helper": argument "$userRep" of method "Svc\ProfileBundle\Service\ChangeMailHelper::__construct()" has type "App\Repository\UserRepository" but this class was not found

This is expected behavior. The entity User must be created manually in the application, e.g. by
bin/console make:user

### CODE REVIEW

**Comment by Sven-Ve** [comment]
@nicolas-grekas : Could you help me and approve this PR?
Thank you very much :-)

**Review by Nyholm — CHANGES_REQUESTED** [review]
I cannot merge this because the CI is failing. 

Please rebase your PR so the new CI rules will run. 

Also, you don't need to add all your default config. I would rather remove the the default config and add a link to your bundles documentation.

**Comment by Nyholm** [comment]
Could you make sure the ci is green?

**Comment by Sven-Ve** [comment]
I will create a new, smaller request

**Pull request closed without merging**
