### PR TITLE
API Components Bundle v2-alpha.1

### PR DESCRIPTION
**Pull request by silverbackdan**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by silverbackdan** [comment]
The travis CI is failing because of the bundle being an alpha release - do I need to wait for a stable release to be able to submit my recipe  to this repository?

**Comment by silverbackdan** [comment]
Thanks for the review @Nyholm - I haven't added all the config, it's just a rather big bundle. Nevertheless I see your point and certainly see lots of defaults I should remove there.

With the folder structure I've provided, would this recipe work (once merged) with alpha versions?

**Comment by Nyholm** [comment]
Feel free to make a new PR if you are still interested to finish this.

**Comment by silverbackdan** [comment]
Thanks! Will do. It'll be there eventually.

**Pull request closed without merging**
