### PR TITLE
Added DoctrineFixturesBundle

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q             | A
| ------------- | ---
| License       | MIT

This recipe is an experiment to see if you agree with it. It's OK to create an empty fixtures file when installing the bundle ... or do you prefer just to create an empty `src/DataFixtures/ORM/` dir ... or even just `src/DataFixtures/` to not upset those not using ORM?

### CODE REVIEW

**Comment by fabpot** [comment]
Having the PHP skeleton file sounds good to me.

**Comment by xabbuh** [comment]
Doesn't the bundle provide a command to create a fixtures skeleton? In that case, I would be in favour to remove the example, but only create the directory.

**Comment by javiereguiluz** [comment]
OK, I've removed the fixture file for now. We can revisit this decision if this PR is merged and the best practices for creating fixtures change a bit: https://github.com/doctrine/DoctrineFixturesBundle/pull/189

**Comment by javiereguiluz** [comment]
I don't understand this error from Symfony Bot:

symfony-bot-error

**Comment by Pierstoval** [comment]
@javiereguiluz Tried adding the MIT notice as in the [PR template](https://github.com/symfony/recipes-contrib/blob/master/.github/PULL_REQUEST_TEMPLATE.md)?

**Pull request merged**
