### PR TITLE
add recpies for aziz403/ux-datatable

### PR DESCRIPTION
**Pull request by Aziz403**
| Q             | A
| ------------- | ---
| License       | MIT
| Packagist     | [link](https://packagist.org/packages/aziz403/ux-datatable)

### CODE REVIEW

**Comment by Aziz403** [comment]
i think i have a probleme between github and packagist.
first when i created the repository in github the name was `aziz403/ux-datatablejs`, 
after that i'm create it in packagist with the same name of course `aziz403/ux-datatablejs`
but then I decided to change the name of package to `aziz403/ux-datatable` .
its changed in repository but i don't know how to do that in packagist.
so now bot can't find it with the name `aziz403/ux-datatable`

**Comment by fabpot** [comment]
You need to resubmit it to Packagist and deprecate the old package.

**Comment by Aziz403** [comment]
> You need to resubmit it to Packagist and deprecate the old package.

okay,thanks sure i will do it

**Comment by Aziz403** [comment]
It still gives the same problem!!!
Capture d’écran 2022-12-30 182133

Also, I tried [(duplicate)](https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository) remove the first repo and change it by new repository with the name `aziz403/ux-datatable`.
But I still have the same thing in packagist :
The package name found for your repository is: `aziz403/ux-datatablejs`, press Submit to confirm

**Comment by weaverryan** [comment]
You should tag a new release - i think that'll fix the CI failure, which is complaining about a missing `doctrine/annotations` library I believe (which you have now added to the package).

**Comment by Aziz403** [comment]
@weaverryan thanks i'm really happy by your help.

**Review by weaverryan — APPROVED** [review]

**Pull request merged**
