### PR TITLE
Add recipe for csa/guzzle-bundle

### PR DESCRIPTION
**Pull request by kejwmen**
| Q             | A
| ------------- | ---
| License       | MIT

According to https://github.com/csarrazi/CsaGuzzleBundle/pull/210#issuecomment-340254607 

@csarrazi here is the recipe, but I realized (right now) that apache license is not allowed :(

### CODE REVIEW

**Comment by csarrazi** [comment]
@kejwmen From what I understand, only the contribution to symfony/recipes-contrib needs to be under the MIT license. Not the bundles or libraries themselves.

@javiereguiluz Could you clarify?

**Comment by csarrazi** [comment]
See symfony/flex#221

**Comment by kejwmen** [comment]
@csarrazi looks that I missed news about it, great to hear!

Updated PR description.

It would be great to update [validation part](https://github.com/symfony/recipes#validation) of recipes readme, but I have no idea what exactly the current rules are, should I just create an issue for that @javiereguiluz ?

**Comment by csarrazi** [comment]
👍 LGTM

**Comment by csarrazi** [comment]
Hi @Nyholm. This is strange. Indeed, FrameworkBundle 4.0 is actually whitelisted: https://github.com/csarrazi/CsaGuzzleBundle/blob/master/composer.json#L12

Which version of `csa/guzzle-bundle` did you try installing? Only version 3.0 will support Symfony 3.4+

**Comment by csarrazi** [comment]
@kejwmen You should rename the 2.2 folder to 3.0.

**Comment by kejwmen** [comment]
@csarrazi done, and thanks for quick 3.0 release

**Comment by csarrazi** [comment]
You're welcome!

This was pending for some time, and unfortunately it is a bit difficult to find some time outside from work to contribute on a regular basis.

**Comment by kejwmen** [comment]
@Nyholm recipe target version bumped to 3.0, should be fine now.

**Comment by Nyholm** [comment]
I think this looks good. 
Let me know when you tagged a stable version and I'll do a final review.

**Pull request merged**
