### PR TITLE
Add stockopedia disposable package for receipe

### PR DESCRIPTION
**Pull request by kk-r**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by kk-r** [comment]
@fabpot  This is recipe for our private package. Error throws `Package does not exist on Packagist` How do I solve this? Anyone please help. Thanks

**Comment by maxhelias** [comment]
This repository can only work with MIT open-source projects or equivalent.
But you can create your own Symfony Recipe repository here : https://github.com/apps/symfony-flex-server/installations/new
More information here : http://fabien.potencier.org/symfony4-flex-private-repositories.html

**Comment by kk-r** [comment]
@maxhelias  Thanks :+1: . I will update recipe repository.

**Comment by Nyholm** [comment]
It seams like the package is removed. 

#eu-fossa

**Pull request closed without merging**
