### PR TITLE
[MsgPhpUserBundle] add post-install.txt

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. 
Maybe you should be a bit more verbose why I should install maker bundle?

Also, there is no need to move recipes from 0.2 to 0.3. You should **copy** or just modify the 0.2 version. It will apply on 0.3 automatically.

**Comment by ro0NL** [comment]
Updated the post install text :) about 0.2 => 0.3; the `make:user` is only available on my side as of user-bundle:^0.3 (hence the rename). Again im killing 0.2 :)

I kept the eav bundle at 0.2. As you mentioned this will work fine with 0.3

**Comment by Nyholm** [comment]
Sure sure. Could you resolve the merge conflict and I'll be happy to merge.

**Comment by ro0NL** [comment]
Done,

**Pull request merged**
