### PR TITLE
Added a new recipe for SymfonyBundles ODM Fixtures Bundle

### PR DESCRIPTION
**Pull request by khaperets**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by khaperets** [comment]
How to add recipe only for Symfony 4+?

**Comment by Nyholm** [comment]
It seams like you have submitted a recipe without any content. 
Flex is smart enough to be able to install this bundle without a recipe. I suggest to close this PR

**Comment by khaperets** [comment]
This PR makes sense to creating a configuration file after installing the package.

**Comment by Nyholm** [comment]
No, it does not.

**Pull request closed without merging**
