### PR TITLE
Remove league/flysystem-bundle as it is now an official recipe

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| License       | MIT
| Packagist     | -

See https://github.com/symfony/recipes/pull/1067

### CODE REVIEW

**Review by vvasiloi — APPROVED** [review]

**Comment by vvasiloi** [comment]
Hey @chalasr, please rebase your branch, there was an issue with the workflow.

**Comment by chalasr** [comment]
@vvasiloi done. The check is failing for some reason though, unrelated to this PR AFAICT

**Comment by chalasr** [comment]
I guess the failure is due to the fact this PR removes a recipe. 
@fabpot any clue?

**Comment by vvasiloi** [comment]
@chalasr yes, looks like that. I tested yesterday by removing other recipes and got the same error.

**Review by fabpot — APPROVED** [review]

**Pull request merged**
