### PR TITLE
Add allmysms bundle

### PR DESCRIPTION
**Pull request by nicodmf**

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. Could you make Travis and the review bot happy?

**Comment by Nyholm** [comment]
Hey @nicodmf do you want to complete this PR?

**Comment by Nyholm** [comment]
Closing due inactivity. 

#eu-fossa

**Comment by nicodmf** [comment]
Sorry i don't see the comments, is there a way to reopen this PR ? i updated the PR

**Comment by Nyholm** [comment]
No worries. 

It seams like I cannot reopen the PR either,.. Weird.. Feel free to make a new one and I'll be happy to merge.

**Comment by nicodmf** [comment]
Ok, this is here : #658

**Pull request closed without merging**
