### PR TITLE
Survos crawler

### PR DESCRIPTION
**Pull request by tacman**
| Q             | A
| ------------- | ---
| License       | MIT
| Packagist     | removing the recipe

### CODE REVIEW

**Comment by fabpot** [comment]
This PR looks very empty 😄

**Comment by tacman** [comment]
Yeah, I wanted to remove the recipe, as I'm experimenting with a custom installer that works from within the bundle.  While of course it doesn't do as much as recipes does, it copies the config files and updates .gitignore and .env, so it works for almost everything I want, and testing it is much easier.

https://github.com/survos/installer/

**Comment by diimpp** [comment]
Hi @tacman, going to close it for now since it's empty.

**Comment by tacman** [comment]
How do I remove a recipe?

**Comment by diimpp** [comment]
> How do I remove a recipe?

Should be the same as for adding new recipes -- Remove files that no longer needed, commit the changes and create a new PR.

**Pull request closed without merging**
