### PR TITLE
Add recipe for monsieurbiz/sylius-rich-editor-plugin in v2

### PR DESCRIPTION
**Pull request by jacquesbh**
| Q             | A
| ------------- | ---
| License       | MIT

See https://github.com/symfony/recipes-contrib/pull/914 for the v1.

The recipe is almost the same. The routing is a bit different and needs a new version of the recipe.

### CODE REVIEW

**Comment by jacquesbh** [comment]
Isn't the error a bit strange @Nyholm? It cannot read the files?

**Review by Nyholm — APPROVED** [review]
Im happy with this. 
Can you rebase this PR on master to make sure the new CI jobs run?

**Comment by Nyholm** [comment]
Thank you. Do you know why the ci fails to install this package on sf 5?

**Comment by jacquesbh** [comment]
> Thank you. Do you know why the ci fails to install this package on sf 5?

We may have an issue on the dependencies, I'll have a look next week!
Thank you!

**Comment by Nyholm** [comment]
Hey. Dont forget about this PR.

**Comment by vvasiloi** [comment]
Hey @jacquesbh, any news about the dependency issue?

**Review by fabpot — APPROVED** [review]

**Pull request merged**
