### PR TITLE
Add glen/slack-unfurl

### PR DESCRIPTION
**Pull request by glensc**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by glensc** [comment]
I wish I knew how to test this prior merge locally.

So far no docs indicate this can be done. Checked:
- https://github.com/symfony/recipes-contrib#contributing
- https://flex.symfony.com/
- https://symfony.com/doc/5.1/setup/flex.html
- https://github.com/symfony/recipes/blob/af59c6fed6ae2d8929f9ac3a1b9d280a3ebfbfbc/README.rst

**Comment by glensc** [comment]
And is it even possible to use flex for the root package?

```
$ composer recipes:install glen/slack-unfurl -v
Cannot update: some packages are not installed: glen/slack-unfurl
```

**Comment by Nyholm** [comment]
If you mark your PR as "Ready for review", the bot will tell you how to test it. 

See example from other PRs: https://flex.symfony.com/r/github.com/symfony/recipes-contrib/1018

**Comment by Nyholm** [comment]
Feel free to open a new PR if you want to finish this.

**Pull request closed without merging**
