### PR TITLE
Woleet naming convention

### PR DESCRIPTION
**Pull request by germainlecourtoissloop**
| Q             | A
| ------------- | ---
| License       | MIT

Naming convention from the Woleet CTO

### CODE REVIEW

**Review by Nyholm — CHANGES_REQUESTED** [review]
Thank you.

There is no need for the recipe for 1.0. The recipe will only be used for new installs and nobody will install 1.0 over 1.2. 

I also think you should use environment variables for the API token and callback secret.

**Comment by germainlecourtoissloop** [comment]
OK thanks @Nyholm 

So, I remove recipe 1.0 and add %env system ?

**Comment by Nyholm** [comment]
Yes please

**Comment by germainlecourtoissloop** [comment]
Done :)

**Review by Nyholm — APPROVED** [review]
Thank you

**Pull request merged**
