### PR TITLE
kunstmaan/admin-bundle: Disable exception logging by default

### PR DESCRIPTION
**Pull request by acrobat**
| Q             | A
| ------------- | ---
| License       | MIT

The upcoming 5.9 version allows to disable the exception logging module and this is a more sensible default config. The 5.9 version is not yet released, but this PR prepare the recipe already

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Please rebase to run checks again.

**Comment by nicolas-grekas** [comment]
To make the create-project check pass, you need to:
1. add `composer config minimum-stability dev` in `.github/workflows/create-project.yml` just after the existing `composer config` lines
2. update the branch-alias of your bundle to `5.9-dev`

**Comment by acrobat** [comment]
@nicolas-grekas done! But wouldn't that change it for all projects?

Also now fails the validation check, can this be ignored?

**Comment by nicolas-grekas** [comment]
I made the change for all packages in 94f3802
Can you please rebase one more time?

**Comment by acrobat** [comment]
@nicolas-grekas Done! The 4.4 project build works correctly now, 5.x is expected to fail as that bundle is not compatible with sf5 yet.

**Review by nicolas-grekas — APPROVED** [review]

**Pull request merged**
