### PR TITLE
Add GeoSocio Http Serializer Bundle

### PR DESCRIPTION
**Pull request by davidbarratt**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by davidbarratt** [comment]
I updated the license in `1.0.5` but now it says the version is not valid. :(
https://packagist.org/packages/geosocio/http-serializer-bundle

**Comment by javiereguiluz** [comment]
Version 1.0.5 is valid according to Packagist: https://packagist.org/packages/geosocio/http-serializer-bundle  Maybe the problem is that it has just been released and we need to wait a bit?

**Comment by fabpot** [comment]
Version 1.0.5 is indeed not valid. It should be 1.0 I suppose.

**Comment by fabpot** [comment]
I've also just updated the validator to make the error message more explicit (you can see the new error message on this PR).

**Pull request merged**
