### PR TITLE
[JanePHP] Introduce JSON Schema & OpenAPI bundles

### PR DESCRIPTION
**Pull request by Korbeil**
| Q             | A
| ------------- | ---
| License       | MIT

Add recipes for Jane JSON Schema & OpenAPI bundles and remove all recipes that were bad by design.

### CODE REVIEW

**Comment by Korbeil** [comment]
@fabpot It seems it tries to test recipes I deleted in this PR.

I deleted them because @nicolas-grekas told me the `bin/` scripts were dirty and I should make clean bundles for them.

**Comment by Nyholm** [comment]
Could you please rebase your PR so the new CI jobs run?

**Comment by Nyholm** [comment]
Ping

**Comment by fabpot** [comment]
Closing as there is no feedback.

**Pull request closed without merging**
