### PR TITLE
Adding Bref logger

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| License       | MIT

https://github.com/brefphp/logger

FYI @mnapoli

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
There's already a very similar logger wired by default in Symfony. I fear this might be confusing.

**Comment by Nyholm** [comment]
That is true.. and you would not get an error that two services are defining the same alias.

I will comment out the aliases. Thank you for the review

**Comment by nicolas-grekas** [comment]
Sorry to be annoying, but I don't see the point of having a recipe at all :)

**Comment by Nyholm** [comment]
The point is to automatically register the service and to make sure you can use it with zero config in your application. 

With this recipe I can write the class: 

```php
use Bref\Logger\StderrLogger;
class Foo {
  public function __construct(StderrLogger $logger) {
     // ...
  }
}
```

I cannot do this without this recipe.

**Comment by nicolas-grekas** [comment]
Sure, but the best practice is to type hint an interface, and there is one here. Hacking autowiring to save writing configuration is something we should discourage IMHO.

**Comment by Nyholm** [comment]
Oh, I see what you are saying now.. Or what you mean: 

In the HttpKernel component there is a [Logger](https://github.com/symfony/symfony/blob/v4.3.2/src/Symfony/Component/HttpKernel/Log/Logger.php) which does pretty much exact the same thing as `bref/logger`. That class is automatically registered as service `logger` with the alias to `Psr\Log\LoggerInterface`. So the `bref/logger` package is never needed in a Symfony application. 

One could of course make the argument that this recipe would be good for people not using the HttpKernel component. But I think that is an edge case. 

Thank you.

**Comment by mnapoli** [comment]
Here is the current documentation for using Symfony with Bref:

Capture d’écran 2019-06-29 à 13 55 53

(see https://bref.sh/docs/frameworks/symfony.html)

As such I don't think bref/logger is necessary in Symfony.

**Pull request closed without merging**
