### PR TITLE
Add recipe for mmoreram/gearman-bundle 4.1+

### PR DESCRIPTION
**Pull request by pinkeen**
| Q             | A
| ------------- | ---
| License       | MIT

Adds recipe for gearman-bundle. The 4.1 tag does not yet exist but is underway and will support symfony 4.0. Adding doctrine cache provider this way is safe because this config key is merged.

### CODE REVIEW

**Comment by daum** [comment]
@pinkeen The Datatables bundle section of this I think was mistakenly included, right?

**Comment by Nyholm** [comment]
Let me know when you are ready for a review and 4.1 is tagged. I’ll be happy to review and test this recipe. 

FYI, recipes in symfony/recipe-contin cannot have aliases.

**Comment by pinkeen** [comment]
@daum Yes, I must've mistakenly copied it from another recipe

**Comment by daum** [comment]
@pinkeen Ok once those are removed I think we can have it reviewed and tested.

**Comment by pinkeen** [comment]
This is kind of strange. I made a force push to my fork's master the other day. It seems that github includes erroneous commits in the PR. I need to close this PR and reopen a new one.

**Pull request closed without merging**
