### PR TITLE
Add recipe "atlas/symfony"

### PR DESCRIPTION
**Pull request by pmjones**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
@symfony-flex-server review please

**Comment by pmjones** [comment]
Thanks for the approvals! Is there something else I need to do for a merge to take effect?

**Comment by fabpot** [comment]
@pmjones Sorry for the delay, there was a bug in the bot code due to a breaking change in the Github API. This has been fixed now and the bot happily merged your PR now.

**Comment by pmjones** [comment]
@fabpot No worries, and thanks!

**Pull request merged**
