### PR TITLE
Updated recipe

### PR DESCRIPTION
**Pull request by knojector**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
How come you dont need an API key anymore?

**Comment by knojector** [comment]
I reworked the whole bundle and it now only cares about the login for which no API key is required. The old version (that doesn't exist anymore) made additional API requests  to fetch more information.

**Comment by Nyholm** [comment]
Oh no. There are 2 rules a open source maintainer must always do: 
- Always follow Semver
- Never remove tags

I hope you just release version 2.0 next time instead of removing the code.

**Review by Nyholm — APPROVED** [review]
Thank you

**Pull request merged**
