### PR TITLE
Adding `logOutputFile: '/dev/null'`

### PR DESCRIPTION
**Pull request by ThomasLandauer**
See https://github.com/dompdf/dompdf/issues/2810#issuecomment-1070927239 for the reason and https://github.com/dompdf/dompdf/issues/1709#issuecomment-466717959 for the solution

| Q             | A
| ------------- | ---
| License       | MIT
| Packagist     | https://repo.packagist.org/packages/nucleos/dompdf-bundle

### CODE REVIEW

**Comment by vvasiloi** [comment]
Hey @ThomasLandauer, if this options is passed to [Dompdf](https://github.com/dompdf/dompdf), then I think it's better to set it's value to `null` (`logOutputFile: ~`) or another _falsy_ value to disable the logging altogether. Also, `/dev/null` won't work on Windows. 😅

**Comment by ThomasLandauer** [comment]
@vvasiloi Thanks, I changed it to empty string, according to https://github.com/dompdf/dompdf/issues/2810#issuecomment-1070981789
P.S.: It's meant to solve a Linux-only problem (file permission), so I didn't really care about Windows ;-)

**Comment by vvasiloi** [comment]
> @vvasiloi Thanks, I changed it to empty string, according to [dompdf/dompdf#2810 (comment)](https://github.com/dompdf/dompdf/issues/2810#issuecomment-1070981789) P.S.: It's meant to solve a Linux-only problem (file permission), so I didn't really care about Windows ;-)

I understand. I was just pointing that while this fixes an issue on Linux, it introduces another one on Windows.
I know very few (maybe even no one) would deploy this to a Windows server, but a lot still develop on Windows and that's where this would have failed.

**Review by vvasiloi — APPROVED** [review]
Thanks @ThomasLandauer!

**Pull request merged**
