### PR TITLE
Enqueue packages

### PR DESCRIPTION
**Pull request by makasim**
| Q             | A
| ------------- | ---
| License       | MIT

contains https://github.com/symfony/recipes-contrib/pull/59.

Contains recipes for enqueue packages:

* enqueue/amqp-bunny
* enqueue/amqp-lib
* enqueue/async-event-dispatcher
* enqueue/gearman
* enqueue/gps (Google PubSub)
* enqueue/sqs (Amazon SQS)
* enqueue/stomp
* enqueue/redis

### CODE REVIEW

**Comment by makasim** [comment]
@ASKozienko could you please review?

**Comment by makasim** [comment]
@fabpot the PR has an approve from both a person with write access and symfony-bot. I still not able to merge it.

**Comment by stof** [comment]
@fabpot why is there so much approvals here without any changes in the PR ?

**Comment by fabpot** [comment]
Tests :)

**Pull request merged**
