### PR TITLE
Create UploadedFileTypeBundle first recipe

### PR DESCRIPTION
**Pull request by Tilotiti**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Tilotiti** [comment]
I think there is a cache problem with the validation bots ... The tags are created.

I will wait until tomorrow to try again ...

**Comment by Tilotiti** [comment]
I don't understand what appends with Travis, why is it trying to test it with PHP 8 when my bundle is PHP 7 only ?

**Review by Nyholm — APPROVED** [review]
This recipe looks okey. Can you rebase your PR so the new CI jobs run?

**Comment by Nyholm** [comment]
Oh no. It looks like your bundle could not be installed. 

Please make sure the CI is green (It is okey if it fail for Symfony 4.4)

**Comment by Nyholm** [comment]
Ping again =)

**Comment by fabpot** [comment]
Closing as there is no more feedback.

**Pull request closed without merging**
