### PR TITLE
Adding melodiia recipe

### PR DESCRIPTION
**Pull request by Nek-**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nek-** [comment]
Failure related to https://github.com/symfony/recipes-contrib/pull/923

**Comment by Nek-** [comment]
Hello there. @Nyholm can this be approved? :)

**Review by Nyholm — APPROVED** [review]
Yeah, I think it looks about right. 

Thank you

**Comment by Nek-** [comment]
Thanks!

**Pull request merged**
