### PR TITLE
Add sonata-project/notification-bundle recipe

### PR DESCRIPTION
**Pull request by covex-nn**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by covex-nn** [comment]
Directory `metadata/jms_serializer/` of a recipe contains `Entity.SonataNotificationMessage.xml` file with serializer metadata configuration. That file will not be used automaticaly if #293 won't be accepted =(

**Comment by kunicmarko20** [comment]
As we can't determine if the user is using Entities, PHPCR or Documents we can't go this way and we will have to fall back to using easyextends. So you can remove the Entity, serialization and orm configuration. Can you make an RFC on https://github.com/sonata-project/dev-kit and we can further discuss this there?

**Comment by covex-nn** [comment]
@kunicmarko20 i thought, that removing **ORM** annotations will solve that problem =) i should ask first about it, sorry

**Comment by kunicmarko20** [comment]
Good job, now we need packs

**Comment by covex-nn** [comment]
@Nyholm the [README.rst](https://github.com/symfony/recipes-contrib/blob/master/README.rst) says that after a `trusted user` approves PR, it will be automatically  merged; and a `The user is a member of the organizations (publicly visible) for all modified packages` is a `trusted user` too! @kunicmarko20 is a member of @sonata-project, but a PR is still not merged yet. How does magic works? =)

**Comment by covex-nn** [comment]
@symfony-flex-server merge now please

**Comment by kunicmarko20** [comment]
cc @jsala @greg0ire @core23 @OskarStark can someone approve this?

**Comment by kunicmarko20** [comment]
@Nyholm how do we get this merged?

**Comment by covex-nn** [comment]
Maybe someone, not a member of @sonata-project, have to approve PR?

**Comment by covex-nn** [comment]
@symfony-flex-server review please

**Comment by covex-nn** [comment]
@kunicmarko20 @jordisala1991 i hoped, that a member of @sonata-project is a `trusted user` and this feature works. May be we should wait for a approval from other user? not me and not @sonata-project member?

**Comment by jordisala1991** [comment]
how do we become trusted users?

**Comment by jordisala1991** [comment]
`The user is a member of the organizations (publicly visible) for all modified packages.`

Given this description, I should be a trusted user, why can't I merge this?

**Comment by covex-nn** [comment]
> Can someone add a comment on the pull request that should have been merged automatically? I will have a look later on.

@fabpot adding a comment

**Comment by patrickbussmann** [comment]
Is there a reason why pull requests without errors like this will not be merged?

**Comment by greg0ire** [comment]
@patrickbussmann I think a bug is the most probable reason, and it has yet to be determined, see https://github.com/symfony/recipes-contrib/pull/302#issuecomment-384218821

**Comment by fabpot** [comment]
@jordisala1991 you need to approve the pull request, which you have not done yet.

**Comment by OskarStark** [comment]
@fabpot he did and me either and we are both members of sonata-project:
screenshot 2018-05-17 08 51 44

**Comment by covex-nn** [comment]
@symfony-flex-server review please =)

**Comment by fabpot** [comment]
And fixed :)

**Comment by covex-nn** [comment]
Hooray =) Thank you!

**Pull request merged**
