### PR TITLE
Add sapient-bundle recipe

### PR DESCRIPTION
**Pull request by lepiaf**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for the PR. I see that you enable the bundle for "prod" and "dev". Is there a reason why you did not use "all"?

**Comment by lepiaf** [comment]
Hi, 

I did not use `all` because I thought it would be difficult to test functionally an API. For example, I want to test a `GET /api/user/1`, I want to check the json structure.

**Comment by lepiaf** [comment]
I have a subscriber that listen on all kernel response and transform it to return an encrypted body.

**Comment by Nyholm** [comment]
I see your reasoning. I would like my test environment to be as similar to production as possible. By disabling encryption on tests will fail to detect encryption related bugs. 

I would say that best practice is to enable the bundle on all environments. If you agree with me, then the recipe is not needed since Flex is smart enough to install this bundle anyways. 

If you **strongly** disagree, Im okey with merging the PR in its current state. 

What do you want to do?

**Comment by lepiaf** [comment]
Ok, I agree with you.

One more question, does Symfony Flex create a config file for bundle? 

After installing bundle, user need to run a command to configure the bundle. I was thinking it might be easy to have an minimum config file and then copy the generated configuration.

For example, minimum config file do nothing. User will enable ability one by one.
```
sapient:
```

- http://sapient-bundle.readthedocs.io/en/latest/installation.html#symfony-4-without-recipe
- http://sapient-bundle.readthedocs.io/en/latest/reference.html

**Comment by lepiaf** [comment]
I've added a post install message to tell user what to do next.

**Pull request merged**
