### PR TITLE
Bundle for Firebase Cloud Messaging

### PR DESCRIPTION
**Pull request by christophe-mailfert**
| Q             | A
| ------------- | ---
| License       | MIT

Bundle for Firebase Cloud Messaging

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. I think this looks good. Can you check why Travis is red?

**Comment by christophe-mailfert** [comment]
That's strange

Travis said

!!  In CloudMessagingExtension.php line 24:
!!                                              
!!    Notice: Undefined index: cloud_messaging  
!!                                              
!!  

It's working on my project. Any idea ?

**Comment by Nyholm** [comment]
I think you are having some issues in Configuration.php. 

Try:
```
composer create-project symfony/skeleton foo
cd foo
composer config extra.symfony.allow-contrib true
export SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes-contrib/246
composer req "sprintechnology/firebase-cloud-messaging:^1.0"
```
That will reproduce the error for you.

**Comment by christophe-mailfert** [comment]
@Nyholm Thx :)

**Pull request merged**
