### PR TITLE
[added] swoole-bundle.

### PR DESCRIPTION
**Pull request by successgo**
| Q             | A
| ------------- | ---
| License       | MIT

Symfony Flex is a great product.

This PR add flex support for https://github.com/tronfony/swoole-bundle.

> PS: swoole-bundle is working in progress, but I would like to add flex support early, thank you symfony team.

### CODE REVIEW

**Comment by gaodacheng** [comment]
Hey, travis-ci build of symfony3.4 failed, does this matter ?

Could anyone give some tips ?

Thanks a lot.

**Comment by imper86** [comment]
@gaodacheng look at composer.json in your bundle. It requires symfony/console and symfony/framework-bundle ^4.3, that's why 3.4 build fails.

**Comment by Nyholm** [comment]
Thank you for the help reviewing @imper86. 

Support for 3.4 is preferred but not required. @imper86 suggest the fix. 

Im happy with this PR, but Im curious why you want to overwrite bin/console. Are you sure your are handling all enviroment variables correctly now? Wouldn't it be better to call it something differently? `bin/swoole`?

That would avoid issues when you dont want to use swoole, right? Or have I misunderstood?

**Comment by gaodacheng** [comment]
Thank you for following up @Nyholm and thank you @imper86 for your suggestion.

Overwrite of `bin/console` may be a bad idea. I will rename to another one later.

**Comment by Nyholm** [comment]
Friendly ping

**Comment by DickensGao** [comment]
Thanks @Nyholm . I'm so sorry that I have not done any update. Give me some time.

**Comment by Nyholm** [comment]
Another friendly reminder =)

**Pull request closed without merging**
