### PR TITLE
Adding BCCCronManagerBundle 2.6 recipe

### PR DESCRIPTION
**Pull request by samuel4x4**
| Q             | A
| ------------- | ---
| License       | MIT

This PR adds recipes for the BCCCronManagerBundle 2.6 (https://github.com/michelsalib/BCCCronManagerBundle/pull/82 and https://github.com/michelsalib/BCCCronManagerBundle/pull/84)

### CODE REVIEW

**Comment by Nyholm** [comment]
It seams like this recipe is that same as #147, right? 

The recipe for 2.6 will be used when installing 3.1 if no other recipes exists.

**Comment by samuel4x4** [comment]
Hi @Nyholm, thank you for review. I started both 3.1 and 2.6 with the same content but I'm not sure they will stay the same. Maybe some changed should be done on the bundle 2.6 in order to can be used with flex. The validation says "Package must not depend on symfony/symfony", so maybe their 2.6 composer.json can contains explicitly the Symfony components, instead of symfony/symfony. What do you think?

**Comment by Nyholm** [comment]
All (maintained) versions of all bundles should specify symfony components specifically. 

Im just saying, if the recipe for 2.6 and 3.1 is the same, we can remove the recipe for 3.1 and the user will not notice.

**Comment by Nyholm** [comment]
How do you want to do with this PR now hen #147 is merged?

**Comment by samuel4x4** [comment]
I think we can close this one for now.

**Pull request closed without merging**
