### PR TITLE
Support mukadi/wordpress-bundle v1.2.0

### PR DESCRIPTION
**Pull request by mbo2olivier**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. I would be happy to approve this. 

You **could** use the "copy-from-package" feature and move some of your code to your package instead of having it here in the recipe. That would make it simpler for you to version your code and to push new updates. 

Tell me what you want to do.

**Comment by mbo2olivier** [comment]
> 
> 
> Thank you. I would be happy to approve this.
> 
> You **could** use the "copy-from-package" feature and move some of your code to your package instead of having it here in the recipe. That would make it simpler for you to version your code and to push new updates.
> 
> Tell me what you want to do.

Okay, it's not a bad idea. I can move all files into the package except the config ones ? what do you think about that ?

**Comment by Nyholm** [comment]
That sounds great!

**Comment by Nyholm** [comment]
Friendly ping

**Pull request closed without merging**
