### PR TITLE
Add OldSoundRabbitMqBundle recipe

### PR DESCRIPTION
**Pull request by yceruto**
Official Symfony bundle https://github.com/php-amqplib/RabbitMqBundle (761 stars)

### CODE REVIEW

**Comment by yceruto** [comment]
I followed these instructions: https://symfony.sh/r/contrib/20 to test my changes but I don't be able to see the config files after:

    composer req "php-amqplib/rabbitmq-bundle:^1.12"

only this one:

    'OldSound\RabbitMqBundle\OldSoundRabbitMqBundle' => ['all' => true],

I missing something?

**Comment by makasim** [comment]
You have to enable contrib repo 

```
$ composer config extra.symfony.allow-contrib true
```

**Comment by yceruto** [comment]
@makasim Yes, I did that.

**Comment by fabpot** [comment]
@yceruto Wanted to test but as I've added a validation check in between, I cannot anymore until you fix the issue :)

**Comment by yceruto** [comment]
@symfony-bot check again... :) @fabpot styles fixed.

**Comment by yceruto** [comment]
I checked again and nothing... only registers the bundle.

**Comment by yceruto** [comment]
```
Package operations: 3 installs, 0 updates, 0 removals
  - Installing symfony/console (dev-master 1f52319): Loading from cache
    Detected auto-configuration settings for "symfony/console"
    Setting configuration and copying files
  - Installing php-amqplib/php-amqplib (dev-master a39b0fc): Loading from cache
  - Installing php-amqplib/rabbitmq-bundle (v1.12.0): Loading from cache
    Detected auto-configuration settings for "php-amqplib/rabbitmq-bundle"
    Enabling the package as a Symfony bundle
Writing lock file
Generating autoload files
Executing script make cache-warmup [OK]
Executing script assets:install --symlink --relative %WEB_DIR% [OK]
```

Missed `Setting configuration and copying files` after `Detected auto-configuration settings for "php-amqplib/rabbitmq-bundle"`

**Comment by fabpot** [comment]
@yceruto This was a bug, it's fixed now. I've just tested again and it works great now!

**Comment by yceruto** [comment]
Awesome! @fabpot thanks!

**Comment by yceruto** [comment]
Hi @symfony-bot I know you are busy, but shouldn't you check again and change your review to approved if all be well with your rules? please, I hite the red cross :)

**Comment by yceruto** [comment]
Woooh! auto-merge!! :) congratulation!

**Pull request merged**
