### PR TITLE
Add recipe for version 4.x

### PR DESCRIPTION
**Pull request by bytehead**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by bytehead** [comment]
@derrabus as you're contributed lately to version 4.x of the bundle (thanks again!), can you review this?

**Comment by derrabus** [comment]
If I didn't miss anything, your 4.0 recipe is the same as the 3.0 one, correct? In that case, the 3.0 recipe is still fine for 4.0 and we don't need to change anything.

**Comment by bytehead** [comment]
No, the one parameter changed: https://github.com/symfony/recipes-contrib/pull/1100/files#diff-369fcb7e62bddd1844c2703d77b1045e47abd6c0d8e74ecaaadc2035d20d9b36R6 🙃

**Comment by bytehead** [comment]
Issue popped up over here: https://github.com/1up-lab/OneupFlysystemBundle/issues/230

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Oh right. 🙈

**Comment by bytehead** [comment]
Thank you! 🙏

**Pull request merged**
