### PR TITLE
Add [bigoen/mercure-twig-bundle]

### PR DESCRIPTION
**Pull request by safaksaylam**
| Q             | A
| ------------- | ----
| License       | MIT

### CODE REVIEW

**Review by Nyholm — CHANGES_REQUESTED** [review]
I am happy with the mecure bundle but the bigoen_redis does not need a recipe. 

Also, could you make sure Travis is happy?

**Comment by safaksaylam** [comment]
> I am happy with the mecure bundle but the bigoen_redis does not need a recipe.
> 
> Also, could you make sure Travis is happy?
Yes I'm sure. Symfony 3.4 not support from this bundle. Because of this, an error occurred.

**Comment by Nyholm** [comment]
Could you rebase this PR to get the new CI jobs. I need this to work on Symfony 4 or Symfony 5.

**Comment by fabpot** [comment]
Closing as there is no more activity and the PR cannot be merged as is. Feel free to reopen it if you like.

**Pull request closed without merging**
