### PR TITLE
Fix: Autowiring

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| License       | MIT
| Packagist     |  https://packagist.org/packages/datana-gmbh/logz-io-handler

### CODE REVIEW

**Comment by OskarStark** [comment]
@vvasiloi open for a merge? 😃

**Comment by vvasiloi** [comment]
@OskarStark I can't, check failed. :)

**Comment by vvasiloi** [comment]
I fixed it for you the first time, now please do it yourself.

**Comment by OskarStark** [comment]
Oh didn't see your comment 😄 

Fixed 👍

**Review by vvasiloi — APPROVED** [review]

**Pull request merged**
