### PR TITLE
Add recipe for oskarstark/env-var-extension

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by OskarStark** [comment]
@Nyholm can you please merge? Thanks 😃

**Review by Nyholm — COMMENTED** [review]
Thank you. Should we prefix the file name with “oskarstark_”?

**Comment by OskarStark** [comment]
> Thank you. Should we prefix the file name with “oskarstark_”?

Indeed, done 👍

**Comment by OskarStark** [comment]
friendly ping @Nyholm

**Review by Nyholm — APPROVED** [review]
Cool cool cool. 

Thank you

**Pull request merged**
