### PR TITLE
Recipe for mobizel/symfony-capistrano package

### PR DESCRIPTION
**Pull request by loic425**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Pierstoval** [comment]
@Nyholm , it seems that approvals from @lbaey and @smildev, which are part of the @mobizel organization, were not taken in account by the @symfony-flex-server bot to auto-merge the recipe.

Is there any other requirement to fulfill in order to auto-merge the PR?

**Comment by loic425** [comment]
@Nyholm @nicolas-grekas 
I still don't know why this pull request is not auto-merged. Cause we have 2 pull-request approvements from this package's mainteners.

**Comment by loic425** [comment]
Thank you @Nyholm I've updated the package and the Flex recipe.

**Comment by loic425** [comment]
Could you review the changes please? @Nyholm

**Comment by loic425** [comment]
@Nyholm Thanks for the merge. I totally understand your point of view. But Flex seems to be the easiest way to share codes like this and reuse them on several Symfony projects and these files can be upgraded with "composer sync-recipes mobizel/symfony-capistrano --force". Yes this is not a PHP package but it's for Symfony projects, it makes sense to me to use Flex for that :) But if it's not a good practice for Symfony flex recipies maybe Symfony could propose something else for that kind of feature.

**Pull request merged**
