### PR TITLE
Add routmoute/routmoute-discord-bundle

### PR DESCRIPTION
**Pull request by routmoute**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Review by Nyholm — CHANGES_REQUESTED** [review]
I see that you added two recipes, one for 1.0 and one for 1.1. They are a bit different...

Do you expect any new installations to install 1.0? If not, I think we can remove that recipe.

**Comment by routmoute** [comment]
Yes, we can :) ok.

**Review by Nyholm — APPROVED** [review]
Im happy with this. Can you rebase this to make sure the new CI jobs are happy?

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
