### PR TITLE
Add liip/test-fixtures-bundle

### PR DESCRIPTION
**Pull request by alexislefebvre**
| Q             | A
| ------------- | ---
| License       | MIT

Ease installation step: https://github.com/liip/LiipTestFixturesBundle/blob/master/doc/installation.md

Fixes https://github.com/liip/LiipTestFixturesBundle/issues/9

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for the PR. 
It seams like you are adding an empty recipe. Flex is smart enough to install this bundle without a recipe. 

Am I missing something or should we close this one?

**Comment by alexislefebvre** [comment]
With this PR, flex will create a file `liip_test_fixtures.yaml ` to store configuration. Isn't it the recommended configuration?

**Comment by Nyholm** [comment]
No, there is no point in creating an empty file.

**Comment by alexislefebvre** [comment]
Ok, I always thought that it was necessary to enable Symfony bundles. Thanks for the explanation. I'll close my PRs and update the documentation of the 2 bundles.

**Comment by Nyholm** [comment]
No no, Since the composer package is of type "symfony-bundle" and you have your *Bundle.php where it should be, Flex will automatically add your bundle to `config/bundles.php`.

**Comment by alexislefebvre** [comment]
Sorry, in my last comment I meant “I always thought that it was necessary to have an empty configuration to enable a Symfony bundle”.

**Pull request closed without merging**
