### PR TITLE
Add datatables bundle

### PR DESCRIPTION
**Pull request by curry684**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. 

When I try to install this bundle using the recipe (explained [here](https://symfony.sh/r/github.com/symfony/recipes-contrib/172)), I get the following error: 

> Cannot autowire service "Omines\DataTablesBundle\Adapter\Doctrine\ORMAdapter": argument "$registry" of method "__construct()" has type "Symfony\Bridge\Doctrine\RegistryInterface" but this class cannot be loaded.          

Does you bundle miss a requirement?

**Comment by curry684** [comment]
Hmm no I'm just seeing this same error myself. That dependency is completely optional, no idea why Flex is borking on it ([Travis isn't](https://travis-ci.org/omines/datatables-bundle)).

**Comment by curry684** [comment]
Hang on, we're not actually running tests without ORM installed, that's why the autowiring is ofc going insane on it. I'll get it fixed.

**Comment by curry684** [comment]
@nicolas-grekas can I ping you in for your opinion on this? I'm not sure whether this is a bug or a shortcoming in DI, or that I'm just expecting a bit too much magic from autowire.

We have an `ORMAdapter` *shared* service in this bundle, which is autowired to `Symfony\Bridge\Doctrine\RegistryInterface`. Composer.json suggests the `doctrine/doctrine-bundle` if you want to use this specific adapter. I optimistically expected the autowiring in this case to stub the service to an exception, causing it to crash at runtime with something like `Service X is unusable because it depends on unknown class Y`. Instead it crashes at compile time because it tries to autowire a service that may never be used.

For now manual wiring with optional dependency seems to be the only solution, but it seems like we could improve the autowiring behavior here?

**Comment by nicolas-grekas** [comment]
> Service X is unusable because it depends on unknown class Y

wow that'd be awesome (or magic, can't decide yet)
it doesn't work this way currently (not sure it should really for now...)
so yes, manual wiring still has some use cases :)

But in this case, I bet it's because the service is public? You should make it private really, that will remove the failure.

**Comment by curry684** [comment]
It'd be cool magic though   ;)   And not all that tough even I think, it could just wire up a `MissingDependencyServicePlaceholder` or something.

The service itself is private, but tagged and injected in a ServiceLocator so we can resolve it at runtime.

**Comment by curry684** [comment]
@Nyholm I circumvented the issue in a [new release](https://github.com/omines/datatables-bundle/commit/47e4a402cfb3e09a207e530683c18c8d5230300f).

**Pull request merged**
