### PR TITLE
SonataAdminBundle 4.0 WebpackEncore configuration

### PR DESCRIPTION
**Pull request by silasjoisten**
| Q             | A
| ------------- | ---
| License       | MIT

Recipe for SonataAdminBundle with WebpackEncore configuration

see https://github.com/sonata-project/SonataAdminBundle/pull/5461

### CODE REVIEW

**Comment by Nyholm** [comment]
I think I would be happy with this

**Comment by silasjoisten** [comment]
> I think I would be happy with this

What do you mean?

**Comment by Nyholm** [comment]
You have made the PR as "draft". 
Im just saying. If you make it non-draft and CI is green, I would be happy to merge it.

**Comment by silasjoisten** [comment]
Is there any problem when SonataAdminBundle ^4.0 isn't released yet?

**Comment by Nyholm** [comment]
Correct, If 4.0 is not released then CI will be red.

**Comment by silasjoisten** [comment]
I will convert it to a PR if 4.0 is released.

**Comment by Nyholm** [comment]
Any updates of SonataAdminBundle 4.0?

**Comment by Nyholm** [comment]
Friendly ping

**Comment by silasjoisten** [comment]
> Friendly ping

Hi its not released yet. I did not forget this PR. :)

**Comment by OskarStark** [comment]
We are still working in the corresponding PR, but almost good to go 👍🏻

**Comment by Nyholm** [comment]
Friendly reminder to complete this PR.

**Comment by Nyholm** [comment]
Feel free to make a new PR if you are still interested to finish this.

**Pull request closed without merging**
