### PR TITLE
add new bundle SymfonyHealthCheckBundle

### PR DESCRIPTION
**Pull request by Yozhef**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
@symfony-flex-server review please

**Comment by Nyholm** [comment]
@symfony-flex-server review please

**Comment by Nyholm** [comment]
It seams like it was a caching issue. That is why we could not find the package on packagist. 

@Yozhef are you happy with the PR now?

**Comment by Yozhef** [comment]
@Nyholm yes, thanks, can you please merge?)

**Review by Nyholm — APPROVED** [review]
Thank you

**Pull request merged**
