### PR TITLE
[prooph/event-store-symfony-bundle] Fixes incorrect command declaration

### PR DESCRIPTION
**Pull request by gquemener**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by gquemener** [comment]
> It would be better to move this command to the bundle. (https://github.com/symfony/recipes-contrib/pull/798#issuecomment-563326402)

This command is not shipped within the bundle because it is not generic enough. Writing a generic command in the bundle would require a certain amount of time that no contributor has the ability to offer at present time. That is why the command is short, specific to the configuration shipped in the recipe and living by the side of the recipe, on this repository.

Does that make sense?

**Comment by gquemener** [comment]
As this recipe won't work if the `prooph/pdo-event-store` package is not required as well, I am suggesting the (re)creation of a `prooph-pack` here: https://github.com/prooph/prooph-pack/pull/2

**Comment by Nyholm** [comment]
Friendly ping

**Comment by gquemener** [comment]
Hello,

I don't have the will, nor the knowledge, to continue this pull request. As a result, you can close it @Nyholm.

Thanks.

**Comment by Nyholm** [comment]
I understand. 

Thank you for getting back to me.

**Pull request closed without merging**
