### PR TITLE
add sonata admin bundle

### PR DESCRIPTION
**Pull request by aLkRicha**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. Can you have a look why Travis is unhappy?

**Comment by covex-nn** [comment]
@aLkRicha you forgot about routing =) Please add `config/routes/sonata_admin.yaml`:

```yaml
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
```

**Comment by stof** [comment]
Travis is unhappy because SonataAdminBundle requires the templating service to be there, but the Flex skeleton does not enable it by default, and we don't have a recipe for `symfony/templating` to enable it automatically. So it is not enabled when requiring this bundle in an empty Flex project

**Comment by covex-nn** [comment]
@stof with next release of SonataAdminBundle `symfony/templating` won't be needed any more

**Comment by Nyholm** [comment]
Okey, so should we make this recipe for 3.32 then?

**Comment by covex-nn** [comment]
@Nyholm yes, directory-version must by renamed, because only next version will work without `templating` (PR is already merged, we waiting for a release)

**Comment by covex-nn** [comment]
@aLkRicha they finally released [3.31.1](https://github.com/sonata-project/SonataAdminBundle/releases/tag/3.31.1) of `admin-bundle` =)

**Comment by aLkRicha** [comment]
@covex-nn thanks for ping me)

Also, i think that we NEED to store config files in "sonata" folder..

**Comment by covex-nn** [comment]
Do you mean `config/packages/sonata_project/sonata_admin.yaml`? It did not work for `core-bundle`. See https://github.com/symfony/recipes-contrib/pull/249

**Comment by aLkRicha** [comment]
ok, now all checks pass, i'll try to move config file in vendor dir

**Comment by aLkRicha** [comment]
@covex-nn look, it's green :)

**Comment by covex-nn** [comment]
This is because config file is needed in runtime! =) Anyway, i need to check with `SYMFONT_ENDPOINT`, see https://symfony.sh/r/github.com/symfony/recipes-contrib/264

**Comment by covex-nn** [comment]
It does not work =) When config file inside subdirectory, Kernel does not read it.
There is error message: `An exception has been thrown during the rendering of a template ("The block type "sonata.admin.block.admin_list" does not exist").`

I moved `config/packages/sonata/sonata_admin.yaml` to `config/packages/sonata_admin`, cleared cache and error message is gone.

**Comment by covex-nn** [comment]
This is how i tested:
```
composer create-project symfony/skeleton .
composer config extra.symfony.allow-contrib true
SET SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes-contrib/264
composer req "sonata-project/admin-bundle:^3.31"
php -S 127.0.0.1:8000 -t public
```

**Comment by aLkRicha** [comment]
@Nyholm @greg0ire 🥇 :D

**Comment by jordisala1991** [comment]
Ping @Nyholm can we merge this one?

**Pull request merged**
