### PR TITLE
Add logger middleware to the template for TactitianBundle

### PR DESCRIPTION
**Pull request by tomaszhanc**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by rosstuck** [comment]
Hi @Nyholm, thanks for the feedback. :)

I'm not the author of the PR (though I do maintain the tactician package). I feel the comments give starting devs a little help on possible options and sane defaults in the beginning, which is a nice harmless DX improvement.

It wasn't an issue in the initial PR which was reviewed and approved previously, so I don't see any reason to block this one. :)

**Comment by Nyholm** [comment]
> It wasn't an issue in the initial PR which was reviewed and approved previously, so I don't see any reason to block this one. :)

Yeah, I know this is a weird request by me. We are still learning about the processes and how the "perfect recipe" should look. The past few months we have started to not accept recipes with default config or config in comments. The reason is that recipes should not be a replacement for the bundles/package documentation.

**Comment by Nyholm** [comment]
Any updates on this PR?

**Comment by Nyholm** [comment]
Closing due inactivity. #eu-fossa

**Pull request closed without merging**
