### PR TITLE
Add sonata-project/media-odm-pack recipe

### PR DESCRIPTION
**Pull request by covex-nn**
| Q             | A
| ------------- | ---
| License       | MIT

To test a recipe execute following commands:
```bash
composer create-project symfony/skeleton .
composer config extra.symfony.allow-contrib true
export SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes-contrib/410
composer config platform.ext-mongo 1.6.16
composer require sonata-project/media-odm-pack
```

Create `docker-compose.yaml`
```yaml
version: '3.4'

services:
    mongo:
        image: mongo:3.6
        ports:
            - "27017:27017"
        environment:
            MONGO_DATA_DIR: /data/db
        volumes:
          - database:/data/db

volumes:
    database:
```

Execute commands:
```bash
docker-compose up -d
bin/console doctrine:mongodb:schema:create
php -S 127.0.0.1:80 -t public
```

Under Windows (for Docker Toolbox) update `.env` file: change `localhost` in `MONGODB_URL=mongodb://localhost:27017` to a IP from `docker-machine env` output

Visit http://localhost/admin/

### CODE REVIEW

**Comment by covex-nn** [comment]
merge now

**Comment by kunicmarko20** [comment]
Should we ping someone or wait for a review?

**Comment by covex-nn** [comment]
I guess, just wait. PR is ready and will be merged soon anyway like #388

**Comment by covex-nn** [comment]
Thank you! :tada:

**Pull request merged**
